services:
  php:
    image: php:8.1-fpm  # Cambiado a imagen base
    container_name: laravel_php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend/src:/var/www/html
    networks:
      - laravel_net

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_net

  db:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_net

  mobile:
    image: node:18
    container_name: react_native_mobile
    working_dir: /app
    command: tail -f /dev/null  # Añadimos este comando para mantener el contenedor activo
    volumes:
      - ./mobile:/app
      - /app/node_modules
    ports:
      - "8081:8081"
      - "9090:9090"
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
    privileged: true
    restart: unless-stopped  # Añadimos política de reinicio
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge

volumes:
  dbdata: