FROM node:18

RUN apt-get update && apt-get install -y \
    adb \
    android-tools-adb \
    openjdk-11-jdk \
    wget \
    unzip \
    git

WORKDIR /app

RUN npm install -g react-native-cli

EXPOSE 8081

CMD ["npm", "start"]